import { buildStats, percentage } from "./analytics.ts";
import { DATASET_VERSION } from "./model.ts";
import type { MatchRecord } from "./model.ts";
import { buildPressureAnalytics } from "./pressure.ts";
import { activePointEvents, pointDetailsMap, projectScore, scoreSummary } from "./scoring.ts";

export interface CoachReportOptions { opponentIdentity: boolean; matchStats: boolean; timeline: boolean; mentalStates: boolean; mentalNotes: boolean; recommendations: boolean }
export const DEFAULT_REPORT_OPTIONS: CoachReportOptions = { opponentIdentity: true, matchStats: true, timeline: true, mentalStates: false, mentalNotes: false, recommendations: true };
const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

export function buildCoachReport(match: MatchRecord, options: CoachReportOptions = DEFAULT_REPORT_OPTIONS) {
  const stats = buildStats(match.events, match.config); const pressure = buildPressureAnalytics(match); const score = projectScore(match.events, match.config);
  const points = activePointEvents(match.events); const details = pointDetailsMap(match.events); const opponent = options.opponentIdentity ? match.config.opponentName : "Opponent";
  const timeline = points.map((p, index) => `<tr><td>${index + 1}</td><td>${p.payload.winner === "my" ? esc(match.config.myPlayerName) : esc(opponent)}</td><td>${esc(details.get(p.pointGroupId)?.outcome?.replaceAll("_", " ") ?? p.payload.serveResult.replaceAll("_", " "))}</td><td>${esc(scoreSummary(p.payload.scoreAfter, match.config))}</td></tr>`).join("");
  const mental = match.events.filter((e) => e.type === "mental_state_changed").map((e) => `<li>Event ${e.sequence}: ${esc(e.payload.player === "my" ? match.config.myPlayerName : opponent)} — ${esc(e.payload.state.replaceAll("_", " "))}${options.mentalNotes && e.payload.note ? ` · ${esc(e.payload.note)}` : ""}</li>`).join("");
  const pressureRow = (key: "my" | "opponent") => `${pressure[key].won}/${pressure[key].played} (${percentage(pressure[key].won, pressure[key].played)})`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width"><title>Baseline coach report</title><style>body{font:15px system-ui;color:#102c2c;max-width:900px;margin:auto;padding:28px}h1{font-size:32px}.card{background:#f5f1e8;border-radius:16px;padding:18px;margin:14px 0}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.muted{color:#687976}@media print{body{padding:0}.card{break-inside:avoid}}</style></head><body><p class="muted">BASELINE · READ-ONLY COACH REPORT</p><h1>${esc(match.config.myPlayerName)} vs. ${esc(opponent)}</h1><p>${esc(match.config.date)} · ${esc(scoreSummary(score, match.config))}</p>${match.config.tournamentName ? `<p>${esc(match.config.tournamentName)}</p>` : ""}${options.matchStats ? `<section class="card"><h2>Match stats</h2><p>${esc(match.config.myPlayerName)}: ${stats.my.pointsWon} points won · pressure ${pressureRow("my")}</p><p>${esc(opponent)}: ${stats.opponent.pointsWon} points won · pressure ${pressureRow("opponent")}</p><p>Coverage: ${stats.directlyTrackedPoints}/${stats.estimatedTotalPoints} (${stats.coverage}%)</p></section>` : ""}<section class="card"><h2>Observation</h2><p>Pressure results are derived from the score immediately before each tracked point and should be interpreted cautiously when samples are small.</p>${options.recommendations ? `<h2>Recommendation</h2><p>Review one repeatable serve or return pattern from the timeline and use it as the focus for the next practice.</p>` : ""}</section>${options.timeline ? `<section class="card"><h2>Point timeline</h2><table><thead><tr><th>#</th><th>Winner</th><th>Outcome</th><th>Score</th></tr></thead><tbody>${timeline}</tbody></table></section>` : ""}${options.mentalStates ? `<section class="card"><h2>Mental-state progression</h2><p class="muted">Subjective courtside observations—not diagnostic claims.</p><ul>${mental || "<li>Not observed</li>"}</ul></section>` : ""}<section class="card"><h2>Data quality</h2><p>${stats.directlyTrackedPoints} tracked points; ${stats.scoreSyncs} score synchronizations; optional shot data may be incomplete.</p></section><footer class="muted">Generated ${new Date().toISOString()} · dataset ${DATASET_VERSION} · cutoff ${match.events.length} · report v1</footer></body></html>`;
}
